"""
GhostScripter-K1-K2 — Script Model
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import List


@dataclass
class CompilationError:
    line: int
    column: int
    message: str
    severity: str = "error"  # "error" | "warning"

    def __str__(self):
        return f"[{self.severity.upper()}] Line {self.line}: {self.message}"


@dataclass
class ScriptFile:
    """Represents an NSS script file."""

    name: str = ""
    file_path: Path | None = None
    source_code: str = ""
    compiled_code: bytes | None = None
    errors: List[CompilationError] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    # Metadata
    created_date: datetime = field(default_factory=datetime.now)
    modified_date: datetime = field(default_factory=datetime.now)
    dependencies: List[str] = field(default_factory=list)
    global_variables: List[str] = field(default_factory=list)
    functions_called: List[str] = field(default_factory=list)

    # Project context
    script_type: str = "quest"  # quest | dialogue | event | npc
    associated_quest: str | None = None

    # ──────────────────────────────────────────────────────────

    def get_file_path(self) -> Path | None:
        return self.file_path

    def get_compiled_path(self) -> Path | None:
        if self.file_path:
            return self.file_path.with_suffix(".ncs")
        return None

    def get_referenced_variables(self) -> List[str]:
        """Extract all SetGlobal/GetGlobal variable references."""
        pattern = r'(?:Get|Set)Global(?:Number|Boolean|String)\s*\(\s*"([^"]+)"'
        return re.findall(pattern, self.source_code)

    def get_function_calls(self) -> List[str]:
        """Extract all function calls (capitalized identifiers)."""
        pattern = r'\b([A-Z][a-zA-Z0-9_]*)\s*\('
        return list(set(re.findall(pattern, self.source_code)))

    def save_to_disk(self) -> bool:
        """Write source code to disk."""
        if not self.file_path:
            return False
        try:
            self.file_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.file_path, "w", encoding="utf-8") as f:
                f.write(self.source_code)
            self.modified_date = datetime.now()
            return True
        except OSError:
            return False

    def load_from_disk(self) -> bool:
        """Load source code from disk."""
        if not self.file_path or not self.file_path.exists():
            return False
        try:
            with open(self.file_path, encoding="utf-8") as f:
                self.source_code = f.read()
            return True
        except OSError:
            return False

    def has_errors(self) -> bool:
        return any(e.severity == "error" for e in self.errors)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "file_path": str(self.file_path) if self.file_path else None,
            "script_type": self.script_type,
            "associated_quest": self.associated_quest,
            "error_count": len(self.errors),
            "warning_count": len(self.warnings),
        }

    def __str__(self):
        return f"ScriptFile({self.name!r}, {self.script_type})"


# ── Starter Templates ─────────────────────────────────────────

def make_quest_start_template(quest_var: str, state_value: int = 1) -> str:
    return f"""// Quest start script — auto-generated by GhostScripter-K1-K2
// Set quest variable to its active state ({state_value})

void main() {{
    SetGlobalNumber("{quest_var}", {state_value});
}}
"""

def make_quest_complete_template(quest_var: str, state_value: int = 2) -> str:
    return f"""// Quest complete script — auto-generated by GhostScripter-K1-K2

void main() {{
    SetGlobalNumber("{quest_var}", {state_value});
}}
"""


def make_quest_state_template(
    quest_var: str,
    state_value: int,
    state_name: str = "",
) -> str:
    """Build an action script that moves a quest to an arbitrary state."""
    # Keep user-entered labels inside a single comment line so they cannot
    # accidentally turn generated text into invalid NWScript.
    safe_label = " ".join(state_name.splitlines()).replace("*/", "* /").strip()
    label = f" ({safe_label})" if safe_label else ""
    return f"""// Quest state script — auto-generated by GhostScripter-K1-K2
// Set quest state to {state_value}{label}

void main() {{
    SetGlobalNumber("{quest_var}", {state_value});
}}
"""

def make_quest_check_template(quest_var: str) -> str:
    return f"""// Quest conditional check — auto-generated by GhostScripter-K1-K2
// Returns TRUE if quest is in specific state

int StartingConditional() {{
    return (GetGlobalNumber("{quest_var}") == 1);
}}
"""

def make_void_main_template() -> str:
    return """// NWScript — GhostScripter-K1-K2

void main() {
    // Your code here
}
"""

def make_starting_conditional_template() -> str:
    return """// Conditional Script — GhostScripter-K1-K2
// Returns TRUE or FALSE to show/hide dialogue option

int StartingConditional() {
    // Your condition here
    return FALSE;
}
"""
