#!/usr/bin/env python3
"""
build_tools/version_info.py
============================
Generate a Windows VERSIONINFO resource file for PyInstaller.

Called automatically by build.py on Windows, but can also be run standalone:

    python build_tools/version_info.py                        # writes build_tools/version_info.txt
    python build_tools/version_info.py --version 1.2.3       # override version
    python build_tools/version_info.py --output path/out.txt  # custom output path
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _read_version_from_constants() -> str:
    constants = ROOT / "ghostscripter" / "core" / "constants.py"
    if constants.exists():
        for line in constants.read_text(encoding="utf-8").splitlines():
            if line.startswith("APP_VERSION"):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return "1.0.0"


def _version_tuple(version_str: str) -> tuple[int, int, int, int]:
    """Convert '1.2.3' → (1, 2, 3, 0).  Handles up to 4 segments."""
    parts = (version_str.strip().split(".") + ["0", "0", "0", "0"])[:4]
    return tuple(int(p) for p in parts)  # type: ignore[return-value]


def generate(version_str: str, output_path: Path) -> None:
    v = _version_tuple(version_str)
    content = f"""# UTF-8
#
# Windows VERSIONINFO resource for GhostScripter-K1-K2
# Auto-generated by build_tools/version_info.py — do not edit by hand.
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v[0]}, {v[1]}, {v[2]}, {v[3]}),
    prodvers=({v[0]}, {v[1]}, {v[2]}, {v[3]}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName',      u'GhostScripter Project'),
            StringStruct(u'FileDescription',  u'GhostScripter-K1-K2 — KotOR 1 & 2 Modding IDE'),
            StringStruct(u'FileVersion',      u'{version_str}'),
            StringStruct(u'InternalName',     u'GhostScripter-K1-K2'),
            StringStruct(u'LegalCopyright',   u'GPL-3.0 License'),
            StringStruct(u'OriginalFilename', u'GhostScripter-K1-K2.exe'),
            StringStruct(u'ProductName',      u'GhostScripter-K1-K2'),
            StringStruct(u'ProductVersion',   u'{version_str}'),
          ]
        ),
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 1200])])
  ]
)
"""
    output_path.write_text(content, encoding="utf-8")
    print(f"  [OK] Version file written → {output_path}", flush=True)


def main() -> None:
    p = argparse.ArgumentParser(description="Generate Windows VERSIONINFO resource file.")
    p.add_argument("--version", default=None, help="Version string (default: read from constants.py)")
    p.add_argument("--output",  default=str(Path(__file__).parent / "version_info.txt"),
                   help="Output file path")
    args = p.parse_args()

    version = args.version or _read_version_from_constants()
    output  = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    generate(version, output)


if __name__ == "__main__":
    main()
